#!/usr/bin/python

import sys
import getopt
import subprocess
from subprocess import call
import re
import matplotlib.pyplot as loopplt
import matplotlib.pyplot as shareplt

linesize=2000
linescale=linesize/10

def main(filename):
    prevline = 0;
    max = 0;
    i = 0;

    for i in xrange(len(files)):
        filename = files[i]
        with open(filename, "r") as f:
            for line in f:
                words = line.split()
                curline = int(words[1])
                if max < curline - prevline:
                    max = curline - prevline
                    pos = words[0]
                prevline = curline 
        print (pos, max)

def timevsloop(files):
    outfile = "output.png"
    colors = ['red', 'blue']
    maxlist = [0, 0]

    loopplt.xlim([0, 10])
    loopplt.ylim([0, 1])
    
    for i in xrange(len(files)):
        filename = files[i]
        maxdata = 0;
        with open(filename, "r") as f:
            for line in f:
                pass
            words = line.split()
            maxlist[i] = int(words[i]) 


    for i in xrange(len(files)):
        color = colors[i]
        filename = files[i]
        with open(filename, "r") as f:
            for line in f:
                words = line.split()
                loop = int(words[0])
                timestamp = int(words[1])
                offtime = int(words[2])
                x = loop/float(linescale)
                y = timestamp/float(maxlist[i])
                z = 1 - offtime/float(loop + 1)
                loopplt.scatter(x, y, c=color, label=color, alpha=0.5)
                shareplt.scatter(x, z, c=color, label=color, alpha=0.5)
    loopplt.xlabel("Loop Number * 2000")
    loopplt.ylabel("Timestamps")
    loopplt.grid(True)
    loopplt.savefig(outfile)
    loopplt.show()
    shareplt.xlabel("CPU Share")
    shareplt.ylabel("Cumulative Distribution")
    shareplt.grid(True)
    shareplt.savefig(outfile)
    shareplt.show()

if __name__ == "__main__":
    physfile = sys.argv[1]
    virtfile = sys.argv[2]
    files = [physfile, virtfile]
    main(files)
    timevsloop(files)
