#!/usr/bin/python

import sys
import getopt
import subprocess
from subprocess import call
import re
import matplotlib.pyplot as plt

linesize=2000
linescale=linesize/10

def main(filename):
    prevline = 0;
    max = 0;
    i = 0;

    for i in xrange(len(files)):
        filename = files[i]
        with open(filename, "r") as f:
            for line in f:
                words = line.split()
                curline = int(words[1])
                if max < curline - prevline:
                    max = curline - prevline
                    pos = words[0]
                prevline = curline 
        print (pos, max)

def scatterplot(files):
    outfile = "output.png"
    colors = ['red', 'blue']
    maxlist = [0, 0]

    plt.xlim([0, 10])
    plt.ylim([0, 1])
    
    for i in xrange(len(files)):
        filename = files[i]
        maxdata = 0;
        with open(filename, "r") as f:
            for line in f:
                pass
            words = line.split()
            maxlist[i] = int(words[i]) 


    for i in xrange(len(files)):
        color = colors[i]
        filename = files[i]
        with open(filename, "r") as f:
            for line in f:
                words = line.split()
                x = int(words[0])/float(linescale)
                y = int(words[1])/float(maxlist[i])
                plt.scatter(x, y, c=color, label=color, alpha=0.5)
    plt.xlabel("Loop Number * 2000")
    plt.ylabel("Timestamps")
    plt.grid(True)
    plt.savefig(outfile)
    plt.show()

if __name__ == "__main__":
    physfile = sys.argv[1]
    virtfile = sys.argv[2]
    files = [physfile, virtfile]
    main(files)
    scatterplot(files)
