#!/usr/bin/python

import sys
import getopt
import subprocess
from subprocess import call
import re

shortopts = "l:"
guest = "Ubuntu"
ippath = "/VirtualBox/GuestInfo/Net/0/V4/IP"
user = "pri"

def main(argv):
    try:                                
        opts, args = getopt.getopt(argv[1:], 'l:', ['list', 'start=']) 
    except getopt.GetoptError as err:           
        usage()                          
        sys.exit(2)   
    for arg in args:
        if arg == "list":
            call(["VBoxManage", "list", "vms"])
        if arg == "get-ip" or arg == "ssh":
            p = subprocess.Popen(["VBoxManage", "guestproperty", "get", guest,
                ippath], stdout = subprocess.PIPE, stderr = subprocess.PIPE)
            out,err = p.communicate()
            ip = re.findall( r'[0-9]+(?:\.[0-9]+){3}', out)
        if arg == "ssh":
            call(["ssh", guest])


    for opt, arg in opts:
        if opt == "--start":
            call(["VBoxHeadless", "--startvm", arg ])

def usage():
    print "Wrong command bro"             
    print "list , get-ip, --start="

if __name__ == "__main__":
    main(sys.argv)    
